# Generated by Django 4.2.2 on 2023-07-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS'), ('PLN', 'PLN'), ('RUB', 'RUB')], default='UZS', max_length=10),
        ),
    ]
